### PR TITLE
Add tests with Behave

### PR DESCRIPTION
**Pull request by duhow**
Using Gherkin language, this should be easier to maintain and develop new tests.
Added some of the reported issues as a way to prevent regression.

### CODE REVIEW

**Comment by Fubukimaru** [comment]
Looks good, is this finished?

**Comment by duhow** [comment]
Let me enable the new merged #106 before merging.

**Comment by duhow** [comment]
All yours @Fubukimaru !

**Review by Fubukimaru — APPROVED** [review]
Looks good :)

**Pull request merged**
