### PR TITLE
Fail to include files with no ending LF

### LINKED ISSUE #106: [BUG] Including file without ending newline breaks
**Describe the bug**
When including a file that does not end with newline `0x0A`, asmsx build does not work.
Reproducible in f25dd6b a221a91

**Expected output**
To be working.

**Current output**
```
-------------------------------------------------------------------------------
 asMSX v1.0.1-49-ga221a91 MSX cross-assembler. asMSX Team. [2022-01-28]
-------------------------------------------------------------------------------

Parsing file test.asm
Including file test1
Expanding Macros
DONE Expanding Macros
Expanding REPT
Assembling source file test.asm
Parsing error: syntax error
test.asm, line 3: syntax error
```

**Code**

```assembly
.db "HELLO"
.INCLUDE "incfile"
.db "BYE"
```
**incfile:**
```bash
# force create a file without newline
echo -n '.db "WORLD"' > incfile
```

```bash
❯ cat \~tmppre.0
#file "test.asm"
#line 1
.db "HELLO"
#file "incfile"
#file "test.asm"
#line 3
.db "WORLD".db "BYE"
```

**Additional context**

### PR DESCRIPTION
**Pull request by duhow**
Fixes #106

### CODE REVIEW

**Comment by duhow** [comment]
Test is added in #105 ,  will be enabled (remove WIP) once this is merged.

**Comment by duhow** [comment]
Although, file line position is now moved +1 line...
```bash
❯ cat \~tmppre.0
#file "test.asm"
#line 1
.db "HELLO"
#file "include.com"
#file "test.asm"
#line 3
.db "WORLD"
#line 4
.db "BYE"
```

**Comment by duhow** [comment]
Nevermind. Fixed.

**Review by Fubukimaru — COMMENTED** [review]
Looks great, thanks!

**Review by Fubukimaru — APPROVED** [review]

**Pull request merged**
